### ISSUE TITLE
Juniper 

### ISSUE THREAD

**Issue by Xlabjun** [GSA-TTS/identity-dev-docs#530]
Xlabjun:patch-3
```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/526
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/529
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/528
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/522
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/497
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/519
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/496
- [ ] .circleci
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/527
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/520
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/518
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/513
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/512
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/516
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/517
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/515
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/514
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/507
- [ ] https://cdn.jsdelivr.net/npm/anchor-js/anchor.min.js
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/511
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/510
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/505
- [ ] https://github.com/GSA-TTS/identity-dev-docs/pull/504
```
